### ISSUE TITLE
MCU Error t5uid1_ping unkown command

### ISSUE THREAD

**Issue by blondsign** [Thinkersbluff/DGUS-Reloaded_for_CR6-DWIN-SET_Component#16]
### Discussed in https://github.com/Thinkersbluff/DGUS-Reloaded_for_CR6-DWIN-SET_Component/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **blondsign** February  2, 2023</sup>
Hi there I got following error message on my CR 6 SE 4.5.2 board. Can you provide me any solution? 

This is my make menuconfig 

<img width="1160" alt="Bildschirm­foto 2023-02-02 um 15 55 17" src="https://user-images.githubusercontent.com/10729351/216358726-978fe7fb-4a44-49a1-986b-36c9cb8bd4d5.png">

and this is the error in Klipper (Mainsail OS)

<img width="610" alt="Bildschirm­foto 2023-02-02 um 15 56 40" src="https://user-images.githubusercontent.com/10729351/216358991-6e255c5d-7f13-4ee8-bd5c-bf1823b243d5.png">

I hardly tried to follow your guidance.. but unfortunately I fail.. 
Thanks for your help!

</div>

**Comment by Thinkersbluff** [comment]
You are the first person I know with a 4.5.2 board on which to test this theory, so I hope this works flawlessly.

The regular Klipper installation instructions call for precisely the same Make Menuconfig settings for all three of the Creality motherboards (4.5.2, 4.5.3 and 1.1.0.3 ERA).

If that holds true, here, you should be able to flash the precompiled bin file in this folder to your motherboard:

https://github.com/Thinkersbluff/DGUS-Reloaded_for_CR6-Klipper_Component/tree/DGUS-ReloadedForCR6/Related%20Changes/If%20you%20have%20an%20ERA%201.1.0.3%20motherboard/Flash%20this%20%20to%20the%20motherboard

The "usual rules" about having to rename the bin file each time you try again will apply, if the first flash does not work.

Remember that you will also have to change the serial interface id in the [mcu] section of your printer.cfg file, to get past that unknown ping command. (See |Where's my serial port?| in https://www.klipper3d.org/FAQ.html)

**Comment by blondsign** [comment]
Hi @Thinkersbluff, 
I was able to solve the Issue. Unfortunately the firmware was not flashed, because I didn't changed the name of the file (not the same name as last flash is allowed). Now I am very happy with a running screen. Thanks a lot for the quick help and reply.

**Comment by Thinkersbluff** [comment]
For the sake of others who have the 4.5.2 board, please confirm what make menuconfig worked for you?

**Comment by blondsign** [comment]
Both ways.. Pre-compiled, as well as STM32F03 -> 28kiB Bootloader -> USART1 PA10/PA9 -> Screen -> USART3 (PB11/PB10)

**Comment by Thinkersbluff** [comment]
Oh good!
So I can safely update the documentation here to say that the same klipper.bin file works on all 3 Creality boards. 
Thank you!

**Comment by blondsign** [comment]
Yes should be fine. Thank you for creating this nice thing!
